services:
  # Router
  router01:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: router01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    ports:
      - 27101:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - router01_db:/data/db
      - router01_config:/data/configdb
    networks:
      - masternet
  router02:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: router02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - router02_db:/data/db
      - router02_config:/data/configdb
    ports:
      - 27102:27017
    restart: always
    networks:
      - masternet

  # Config Servers
  configsvr01:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: configsvr01
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - configsvr01_db:/data/db
      - configsvr01_config:/data/configdb
    ports:
      - 27201:27017
    restart: always
    networks:
      - masternet
  configsvr02:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: configsvr02
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - configsvr02_db:/data/db
      - configsvr02_config:/data/configdb
    ports:
      - 27202:27017
    restart: always
    networks:
      - masternet
  configsvr03:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: configsvr03
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - configsvr03_db:/data/db
      - configsvr03_config:/data/configdb
    ports:
      - 27203:27017
    restart: always
    networks:
      - masternet

volumes:
  router01_db:
  router01_config:

  router02_db:
  router02_config:

  configsvr01_db:
  configsvr01_config:

  configsvr02_db:
  configsvr02_config:

  configsvr03_db:
  configsvr03_config:

networks:
  masternet:
    driver: bridge
