version: '3'

services:
  ## Shards
  ## Shards 01
  shard01-a:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard01-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard01_a_db:/data/db
      - shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard01-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard01_b_db:/data/db
      - shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
  shard01-c:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard01-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard01_c_db:/data/db
      - shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  shard02-a:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard02-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard02_a_db:/data/db
      - shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard02-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard02_b_db:/data/db
      - shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always
  shard02-c:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard02-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard02_c_db:/data/db
      - shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always

  ## Shards 03
  shard03-a:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard03-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard03_a_db:/data/db
      - shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard03-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard03_b_db:/data/db
      - shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always
  shard03-c:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard03-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard03_c_db:/data/db
      - shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

volumes:
  shard01_a_db:
  shard01_a_config:

  shard01_b_db:
  shard01_b_config:

  shard01_c_db:
  shard01_c_config:

  shard02_a_db:
  shard02_a_config:

  shard02_b_db:
  shard02_b_config:

  shard02_c_db:
  shard02_c_config:

  shard03_a_db:
  shard03_a_config:

  shard03_b_db:
  shard03_b_config:

  shard03_c_db:
  shard03_c_config: