version: "3"

services:
  ## Router
  router01:
    image: mongo:latest
    container_name: router01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
    networks:
      - cluster
  router02:
    image: mongo:latest
    container_name: router02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_router02_db:/data/db
      - mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    networks:
      - cluster

  ## Config Servers
  configsvr01:
    image: mongo:latest
    container_name: configsvr01
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    networks:
      - cluster
  configsvr02:
    image: mongo:latest
    container_name: configsvr02
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr02_db:/data/db
      - mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    networks:
      - cluster
  configsvr03:
    image: mongo:latest
    container_name: configsvr03
    command: mongod --port 27017 --configsvr --replSet rs-config-server --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr03_db:/data/db
      - mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    networks:
      - cluster


volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:

  mongodb_cluster_router02_db:
  mongodb_cluster_router02_config:

  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:

  mongodb_cluster_configsvr02_db:
  mongodb_cluster_configsvr02_config:

  mongodb_cluster_configsvr03_db:
  mongodb_cluster_configsvr03_config:

networks:
  cluster:
    driver: bridge
