version: '3'

services:
  # Shard
  shard-01-a:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard-01-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard_a_db:/data/db
      - shard_a_config:/data/configdb
    ports:
      - 27301:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard-01-b:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard-01-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard_b_db:/data/db
      - shard_b_config:/data/configdb
    ports:
      - 27302:27017
    restart: always
  shard-01-c:
    build: 
      context: mongodb
    image: mongodb:latest
    container_name: shard-01-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - shard_c_db:/data/db
      - shard_c_config:/data/configdb
    ports:
      - 27303:27017
    restart: always

volumes:
  shard-01_a_db:
  shard-01_a_config:

  shard-01_b_db:
  shard-01_b_config:

  shard-01_c_db:
  shard-01_c_config: